# Site
name: "Genesis"
title: "Genesis"
description: "Let's learn and explore together..."
logo: 'assets/images/logo6.png'
favicon: 'assets/images/logo.png'
baseurl: /
#baseurl: /Genesis-z.github.io
google_analytics: 'UA-167890483-1'
disqus: 'Genesis'
mailchimp-list: 'https://github.us10.list-manage.com/subscribe/post?u=145fd0db654a848f2210027e9&amp;id=9f918ad6cc'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Prince
    display_name: Prince
    avatar: 'assets/images/dp1.jpeg'
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: kirankumarxavier@yahoo.com
    web: https://www.linkedin.com/in/kiran-kumar-a5455b154/
    twitter: https://twitter.com/prince_9210
    description: "Author of Genesis, A technical consultant with experience in Information technology and services. Love exploring and developing new innovative and interesting stuffs. Knowledgeable in an assortment of programming languages, scripting languages, operating systems, and applications."
  john:
    name: Jose
    display_name: Jose    
    avatar: 'assets/images/grim.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: naveenjose97x@outlook.com
    web: https://www.linkedin.com/in/naveenkumar-xavier/
    twitter: https://twitter.com/Naveen25X
    description: "Software Engineer with brief experience working with C, C++ and Python language. Knowledgable in Linux and Agile methodologies with 2 years of working experience. Passionate towards exploring new stuffs and expanding knowledge. In a pursuit, learning Networking and Communications."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-9949060398940999"
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
